pipeline_update_db

diff --git a/.github/workflows/db_migration.yml b/.github/workflows/db_migration.yml
--- a/.github/workflows/db_migration.yml
+++ b/.github/workflows/db_migration.yml
@@ -1,4 +1,4 @@
-name: Initializing Database
+name: Initialization Database
 
 on:
   workflow_dispatch:
@@ -8,15 +8,10 @@ permissions:
   contents: read
 
 jobs:
-  init-db:
+  init_db:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
-        with:
-          repository: Arvind1297/banking-app-2-tier
-          ref: main
-
       - uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::514454346636:role/github-action-deploy-role
@@ -24,7 +19,44 @@ jobs:
 
       - name: Upload file on S3
         run: |
-          aws s3 mb s3://514454346636-devops-scripts --region us-east-1 2>/dev/null || true
-          aws s3 cp init.sql s3://514454346636-devops-scripts/init.sql
-          aws s3 cp init.py s3://514454346636-devops-scripts/init.py
-          echo "✅ Files Uploaded to bucket.."
+          aws s3 mb s3://514454346636-devops-scripts --region us-east-1 || echo "Bucket already exists"
+          aws s3 cp init.sql s3://514454346636-devops-scripts/init.sql --region us-east-1
+          aws s3 cp init.py s3://514454346636-devops-scripts/init.py --region us-east-1
+          echo "✅ Files Uploaded to bucket......"
+      - name: Initializing Database on RDS using EC2
+        run: |
+          CMD_ID=$(aws ssm send-command \
+            --targets "Key=tag:App,Values=flask" \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{"commands":[
+              "aws s3 cp s3://514454346636-devops-scripts/init.sql",
+    
+              "python3 /tmp/init.py" ,
+              "rm -rf /tmp/init.sql /tmp/init.py"
+            ]}' \
+            --query 'Command.CommandId'
+            --output text
+            --region us-east-1)
+          echo "cmd_id"=$"CMD_ID" >> $GITHUB_OUT  
+      - name: Show Results
+        run: |
+          sleep 30
+
+          aws ssm list-command-invocations \
+            --command-id "${{steps.init_db.outputs.cmd_id}}" \
+            --details \
+            --region us-east-1 \
+            --output text
+
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{steps.init_db.outputs.cmd_id}}" \
+            --query 'CommandInvocations[*].Status' \
+            --output text \
+            --region us-east-1)
+
+          if [[ "$FAILED" == "Failed" ]]; then
+            echo "::error::Database Initialization Failed on RDS"
+            exit 1
+          else
+            echo "✅ Database Initialized Successfully on RDS"
+          fi
